Repository deadlock-wiki/deadbot, pull requests merged in 2024-11, with the labels that each got.

#92 Feature/Hero is new player recommended flag
  output-data/csv/hero-data.csv
  output-data/json/hero-data.json
  output-data/json/hero-meaningful-stats.json
  src/deadbot.py
  src/decompiler/decompile.py
  src/parser/parsers/heroes.py
Labels: enhancement

#97 Bugfix/fix stake t3 description
  output-data/changelogs/date/08-16-2024.json
  output-data/changelogs/date/08-22-2024.json
  output-data/changelogs/date/08-29-2024.json
  output-data/changelogs/date/09-12-2024.json
  output-data/changelogs/date/10-24-2024.json
  output-data/changelogs/date/10-29-2024.json
  output-data/changelogs/date/11-01-2024.json
  output-data/changelogs/hero/Bebop.json
  output-data/changelogs/hero/General.json
  output-data/changelogs/hero/Grey Talon.json
  output-data/changelogs/hero/Mirage.json
  output-data/changelogs/hero/Paradox.json
  output-data/changelogs/item/General.json
  output-data/changelogs/item/Improved Burst.json
  output-data/changelogs/item/Metal Skin.json
  output-data/changelogs/item/Siphon Bullets.json
  output-data/changelogs/raw/10-29-2024.txt
  output-data/changelogs/raw/11-01-2024.txt
  output-data/csv/hero-data.csv
  output-data/csv/item-data.csv
  output-data/json/ability-data.json
  output-data/json/ability_ui.json
  output-data/json/hero-data.json
  output-data/json/item-data.json
  output-data/localizations/brazilian.json
  output-data/localizations/czech.json
  output-data/localizations/english.json
  output-data/localizations/french.json
  output-data/localizations/german.json
  output-data/localizations/indonesian.json
  output-data/localizations/italian.json
  output-data/localizations/koreana.json
  output-data/localizations/latam.json
  output-data/localizations/polish.json
  output-data/localizations/russian.json
  output-data/localizations/schinese.json
  output-data/localizations/spanish.json
  output-data/localizations/thai.json
  output-data/localizations/turkish.json
  output-data/localizations/ukrainian.json
  output-data/version.txt
  src/parser/parsers/items.py
  src/parser/parsers/souls.py
  src/utils/string_utils.py
Labels: bug

#102 Bugfix/remove panel tags and added bolding for other span classes
  output-data/csv/item-data.csv
  output-data/json/item-data.json
  output-data/localizations/brazilian.json
  output-data/localizations/czech.json
  output-data/localizations/english.json
  output-data/localizations/french.json
  output-data/localizations/german.json
  output-data/localizations/indonesian.json
  output-data/localizations/italian.json
  output-data/localizations/koreana.json
  output-data/localizations/latam.json
  output-data/localizations/polish.json
  output-data/localizations/russian.json
  output-data/localizations/schinese.json
  output-data/localizations/spanish.json
  output-data/localizations/thai.json
  output-data/localizations/turkish.json
  output-data/localizations/ukrainian.json
  output-data/version.txt
  src/utils/string_utils.py
Labels: bug

#101 Feature/weapon move speed mult
  output-data/changelogs/changelogs.json
  output-data/changelogs/raw/45689.txt
  output-data/changelogs/versions/45689.json
  output-data/csv/hero-data.csv
  output-data/json/hero-data.json
  output-data/json/hero-meaningful-stats.json
  output-data/localizations/french.json
  output-data/localizations/german.json
  output-data/localizations/indonesian.json
  output-data/localizations/italian.json
  output-data/localizations/koreana.json
  output-data/localizations/latam.json
  output-data/localizations/polish.json
  output-data/localizations/russian.json
  output-data/localizations/schinese.json
  output-data/localizations/thai.json
  output-data/localizations/turkish.json
  output-data/localizations/ukrainian.json
  output-data/version.txt
  src/parser/parsers/heroes.py
Labels: enhancement

#100 Feature/remove hero bound abilities
  src/parser/parser.py
Labels: enhancement

#127 Hotfix/boon mapping
  src/parser/maps.py
  src/utils/string_utils.py
Labels: hotfix

#128 Hotfix/Hero is selectable flag
  src/parser/parsers/heroes.py
Labels: hotfix

#130 Feature/herolab patch note
  input-data/README.md
  input-data/changelog_configs.json
  input-data/changelogs.json
  input-data/raw-changelogs/herolab_2024_10_29.txt
  input-data/raw-changelogs/herolab_2024_11_07.txt
  src/changelogs/fetch_changelogs.py
  src/changelogs/parse_changelogs.py
  src/changelogs/tags.py
  src/deadbot.py
  src/decompiler/decompile.py
  src/decompiler/localization.py
  src/parser/parser.py
  src/parser/parsers/heroes.py
Labels: enhancement
